const dummy = [
  {
    id: 1,
    title: "안양의 신멘",
    content: "안양에서 맛본 신멘.. 지려따",
    regUser: "양영조",
    regDateTime: "2024-02-26",
    modUser: "양영조",
    modDateTime: "2024-02-29",
    delYn: "N",
    delDateTime: "",
    delDescription: "",
    useYn: "Y",
  },
  {
    id: 2,
    title: "서울의 맛집",
    content: "서울에서 먹은 음식이 정말 맛있었습니다!",
    regUser: "김현진",
    regDateTime: "2024-02-26",
    modUser: "김현진",
    modDateTime: "2024-02-26",
    delYn: "N",
    delDateTime: "",
    delDescription: "",
    useYn: "Y",
  },
  {
    id: 3,
    title: "부산의 향토음식",
    content: "부산에서 먹은 향토음식이 정말 맛있었습니다!",
    regUser: "양영민",
    regDateTime: "2024-02-26",
    modUser: "양영민",
    modDateTime: "2024-02-26",
    delYn: "N",
    delDateTime: "",
    delDescription: "",
    useYn: "Y",
  },
  {
    id: 4,
    title: "제주도의 특산물",
    content: "제주도에서 먹은 특산물이 정말 신선하고 맛있었습니다!",
    regUser: "김선미",
    regDateTime: "2024-02-26",
    modUser: "김선미",
    modDateTime: "2024-02-26",
    delYn: "N",
    delDateTime: "",
    delDescription: "",
    useYn: "Y",
  },
  {
    id: 5,
    title: "대전의 로컬맛집",
    content: "대전에서 찾은 로컬맛집이 정말 좋았습니다!",
    regUser: "양영조",
    regDateTime: "2024-02-26",
    modUser: "양영조",
    modDateTime: "2024-02-26",
    delYn: "N",
    delDateTime: "",
    delDescription: "",
    useYn: "Y",
  },
  {
    id: 6,
    title: "인천의 해산물 요리",
    content: "인천에서 먹은 해산물 요리가 정말 신선했습니다!",
    regUser: "김현진",
    regDateTime: "2024-02-26",
    modUser: "김현진",
    modDateTime: "2024-02-26",
    delYn: "N",
    delDateTime: "",
    delDescription: "",
    useYn: "Y",
  },
  {
    id: 7,
    title: "경주의 전통음식",
    content: "경주에서 먹은 전통음식이 정말 맛있었습니다!",
    regUser: "양영민",
    regDateTime: "2024-02-26",
    modUser: "양영민",
    modDateTime: "2024-02-26",
    delYn: "N",
    delDateTime: "",
    delDescription: "",
    useYn: "Y",
  },
  {
    id: 8,
    title: "강릉의 해산물 요리",
    content: "강릉에서 먹은 해산물 요리가 정말 신선했습니다!",
    regUser: "김선미",
    regDateTime: "2024-02-26",
    modUser: "김선미",
    modDateTime: "2024-02-26",
    delYn: "N",
    delDateTime: "",
    delDescription: "",
    useYn: "Y",
  },
];

export default dummy;
